[package]
name = "dsc-editor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Profile editor for DCS Signal Converter"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2", features = [] }
dsc-bios = { path = "../../crates/dsc-bios" }
dsc-config = { path = "../../crates/dsc-config" }
dsc-engine = { path = "../../crates/dsc-engine" }
