[package]
name = "wctrl-editor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Profile editor for the WinCtrl signal converter"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2", features = [] }
wctrl-bios = { path = "../../crates/wctrl-bios" }
wctrl-config = { path = "../../crates/wctrl-config" }
wctrl-engine = { path = "../../crates/wctrl-engine" }
